export const signalColorTokens = {
  brand: {
    primary: '#FF0025',
    secondary: '#001A41',
  },
  text: {
    red: '#FF0025',
    valid: '#008E53',
    info: '#0050AE',
    error: '#BC1D42',
    warning: '#D9801F',
    primary: '#001A41',
    secondary: '#4E5764',
    disable: '#B3BAC6',
    white: '#FFFFFF',
  },
  background: {
    primary: '#ED0226',
    secondary: '#001A41',
    neutral200: '#E9E8ED',
    neutral300: '#CCCFD3',
    disable: '#F5F6FA',
    disable01: '#F1F1F4',
    warm: '#F6F3F3',
    valid: '#EDFCF0',
    info: '#E7F5FC',
    info02: '#E9F6FF',
    error: '#FDDDD4',
    warning: '#FEF3D4',
    white: '#FFFFFF',
    gradientPrimary: '#ED0226',
    gradientSecondary: '#001A41',
    gradientBanner01Start: '#CD0A45',
    gradientBanner01End: '#FD2B77',
    gradientBanner02Start: '#ED0226',
    gradientBanner02End: '#FDA22B',
    gradientBanner03Start: '#B90024',
    gradientBanner03Middle: '#FF0025',
    gradientBanner03End: '#FD195E',
  },
  linkText: {
    text: '#0050AE',
  },
  productIcon: {
    red: '#FF0025',
    primary: '#001A41',
    white: '#FFFFFF',
    disable: '#4E5764',
  },
  systemIcon: {
    valid: '#008E53',
    info: '#0050AE',
    error: '#DB2941',
    warning: '#FDA22B',
  },
  divider: {
    default: '#EDECF0',
  },
  stroke: {
    default: '#EDECF0',
    primary: '#CCD1D9',
    neutral300: '#CCCFD3',
    warning: '#FED27F',
    valid: '#008E53',
    info: '#0050AE',
    error: '#BC1D42',
    white: '#FFFFFF',
  },
} as const;

export const colors = {
  textPrimary: signalColorTokens.text.primary,
  iconSecondary: signalColorTokens.productIcon.primary,
  bodySecondary: signalColorTokens.text.secondary,
  borderMuted: signalColorTokens.stroke.default,
  borderPrimary: signalColorTokens.stroke.primary,
  surfaceWarm: signalColorTokens.background.warm,
  surfaceDefault: signalColorTokens.background.white,
  surfaceInfo: signalColorTokens.background.info02,
  surfaceDisabled: signalColorTokens.background.disable01,
  shadowLow: '#9E9E9E',
} as const;

export type ColorToken = keyof typeof colors;
