import { signalColorTokens } from './colors';
import { radius } from './radius';
import { spacing } from './spacing';
import { typography } from './typography';

export const componentTokens = {
  button: {
    sizes: {
      large: {
        height: 40,
        minWidth: 328,
        iconSize: 24,
        gap: spacing.buttonGap,
        typography: typography.body1Bold,
      },
      medium: {
        height: 32,
        minWidth: 328,
        iconSize: 20,
        gap: spacing.buttonGap,
        typography: typography.body2Bold,
      },
      small: {
        height: 20,
        minWidth: 87,
        iconSize: 16,
        gap: spacing.iconGapSmall,
        typography: typography.labelBold,
      },
    },
    radius: radius.pill,
    variants: {
      primary: {
        backgroundColor: signalColorTokens.background.primary,
        borderColor: signalColorTokens.background.primary,
        textColor: signalColorTokens.text.white,
        iconColor: signalColorTokens.text.white,
      },
      secondary: {
        backgroundColor: signalColorTokens.background.white,
        borderColor: signalColorTokens.brand.primary,
        textColor: signalColorTokens.brand.primary,
        iconColor: signalColorTokens.brand.primary,
      },
      text: {
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        textColor: signalColorTokens.text.info,
        iconColor: signalColorTokens.systemIcon.info,
      },
    },
  },
  optionCard: {
    width: 327,
    minHeight: 44,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.sm,
    radius: radius.optionCard,
    borderWidth: 1,
    states: {
      default: {
        backgroundColor: signalColorTokens.background.white,
        borderColor: signalColorTokens.stroke.primary,
        textColor: signalColorTokens.text.primary,
        iconColor: signalColorTokens.productIcon.primary,
      },
      selected: {
        backgroundColor: signalColorTokens.background.info02,
        borderColor: signalColorTokens.stroke.primary,
        textColor: signalColorTokens.text.primary,
        iconColor: signalColorTokens.productIcon.primary,
      },
      disabled: {
        backgroundColor: signalColorTokens.background.disable01,
        borderColor: signalColorTokens.stroke.primary,
        textColor: signalColorTokens.text.disable,
        iconColor: signalColorTokens.productIcon.primary,
      },
    },
  },
  bottomSheet: {
    mobileWidth: 375,
    contentWidth: 327,
    overlayColor: signalColorTokens.brand.secondary,
    overlayOpacity: 0.5,
    maxHeight: 660,
    fullPageMaxHeight: 720,
    topRadius: radius.bottomSheet,
    headerRadius: radius.sheetHeader,
    headerPaddingTop: spacing.sheetHorizontal,
    horizontalPadding: spacing.sheetHorizontal,
    componentGap: spacing.lg,
    stickyGap: spacing.md,
    stickyPaddingTop: spacing.lg,
    stickyPaddingBottom: spacing.sheetBottom,
  },
  skeleton: {
    color: signalColorTokens.background.neutral200,
    cardBorderColor: signalColorTokens.stroke.primary,
    title: {
      width: 227,
      height: 5,
      maxWidth: 360,
    },
    button: {
      width: 280,
      height: 40,
      radius: 40,
    },
    card: {
      width: 604,
      height: 88,
      radius: radius.optionCard,
      padding: 24,
      gap: spacing.lg,
      avatarSize: 40,
      titleWidth: 227,
      titleHeight: 4,
    },
  },
  textField: {
    width: 328,
    height: 40,
    labelGap: spacing.sm,
    helperGap: spacing.xxs,
    inputPaddingHorizontal: spacing.md,
    inputPaddingVertical: spacing.sm,
    iconSize: 20,
    loaderIconSize: 24,
    radius: radius.optionCard,
    borderWidth: 1,
    states: {
      enabled: {
        backgroundColor: signalColorTokens.background.white,
        borderColor: signalColorTokens.stroke.neutral300,
        textColor: signalColorTokens.text.primary,
        placeholderColor: signalColorTokens.text.disable,
        helperColor: signalColorTokens.text.secondary,
      },
      focused: {
        backgroundColor: signalColorTokens.background.white,
        borderColor: signalColorTokens.text.info,
        textColor: signalColorTokens.text.primary,
        placeholderColor: signalColorTokens.text.primary,
        helperColor: signalColorTokens.text.secondary,
      },
      filled: {
        backgroundColor: signalColorTokens.background.white,
        borderColor: signalColorTokens.stroke.neutral300,
        textColor: signalColorTokens.text.primary,
        placeholderColor: signalColorTokens.text.primary,
        helperColor: signalColorTokens.text.secondary,
      },
      error: {
        backgroundColor: signalColorTokens.background.white,
        borderColor: signalColorTokens.stroke.error,
        textColor: signalColorTokens.text.primary,
        placeholderColor: signalColorTokens.text.primary,
        helperColor: signalColorTokens.text.error,
      },
      success: {
        backgroundColor: signalColorTokens.background.white,
        borderColor: signalColorTokens.stroke.valid,
        textColor: signalColorTokens.text.primary,
        placeholderColor: signalColorTokens.text.primary,
        helperColor: signalColorTokens.text.valid,
      },
      load: {
        backgroundColor: signalColorTokens.divider.default,
        borderColor: signalColorTokens.stroke.neutral300,
        textColor: signalColorTokens.text.disable,
        placeholderColor: signalColorTokens.text.disable,
        helperColor: signalColorTokens.text.secondary,
      },
      disabled: {
        backgroundColor: signalColorTokens.background.disable01,
        borderColor: signalColorTokens.stroke.neutral300,
        textColor: signalColorTokens.text.disable,
        placeholderColor: signalColorTokens.text.disable,
        helperColor: signalColorTokens.text.disable,
      },
    },
  },
  icon: {
    sizes: {
      major: 24,
      control: 20,
      compact: 16,
    },
    colors: {
      productPrimary: signalColorTokens.productIcon.primary,
      productRed: signalColorTokens.productIcon.red,
      productWhite: signalColorTokens.productIcon.white,
      productDisabled: signalColorTokens.productIcon.disable,
      systemValid: signalColorTokens.systemIcon.valid,
      systemInfo: signalColorTokens.systemIcon.info,
      systemError: signalColorTokens.systemIcon.error,
      systemWarning: signalColorTokens.systemIcon.warning,
      systemSecondary: signalColorTokens.productIcon.primary,
    },
  },
} as const;
