import { componentTokens } from './components';

export const signalIconTokens = {
  size: componentTokens.icon.sizes,
  color: componentTokens.icon.colors,
  systemNames: [
    'ico_placeholder',
    'ico_apps',
    'ico_more',
    'ico_wifi',
    'ico_check',
    'ico_search',
    'ico_more_nav',
    'ico_menu',
    'ico_list',
    'ico_control',
    'ico_download',
    'ico_logout',
    'ico_minus',
    'ico_plus',
    'ico_success_filled',
    'ico_success',
    'ico_failed_filled',
    'ico_stop',
    'ico_close',
    'ico_bill',
    'ico_notification',
    'ico_setting',
    'ico_chevron_down',
    'ico_chevron_left',
    'ico_chevron_right',
    'ico_chevron_up',
    'ico_arrow_left',
    'ico_arrow_right',
    'ico_sort',
    'ico_history',
    'ico_repeat',
    'ico_info',
    'ico_warning',
    'ico_help',
    'ico_simcard',
  ],
  mbcSuggested: {
    station: 'ico_plus',
    gate: 'ico_check',
    terminal: 'ico_success',
    scout: 'ico_search',
    scan: 'ico_simcard',
    balance: 'ico_bill',
    history: 'ico_history',
    settings: 'ico_setting',
    success: 'ico_success_filled',
    error: 'ico_failed_filled',
    warning: 'ico_warning',
    info: 'ico_info',
    close: 'ico_close',
    back: 'ico_arrow_left',
    next: 'ico_arrow_right',
    expand: 'ico_chevron_down',
  },
} as const;

export type SignalSystemIconName = (typeof signalIconTokens.systemNames)[number];
