const FONT_BATIK_BOLD = 'Telkomsel Batik Sans-Bold';
const FONT_POPPINS_REGULAR = 'Poppins-Regular';
const FONT_POPPINS_SEMIBOLD = 'Poppins-SemiBold';
const FONT_POPPINS_MEDIUM = 'Poppins-Medium';

export const typography = {
  h1: {
    fontFamily: FONT_BATIK_BOLD,
    fontSize: 44,
    fontWeight: '700',
    lineHeight: 56,
    letterSpacing: 0,
  },
  h2: {
    fontFamily: FONT_BATIK_BOLD,
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 48,
    letterSpacing: 0,
  },
  h3: {
    fontFamily: FONT_BATIK_BOLD,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 40,
    letterSpacing: 0,
  },
  h4: {
    fontFamily: FONT_BATIK_BOLD,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 40,
    letterSpacing: 0,
  },
  h5: {
    fontFamily: FONT_BATIK_BOLD,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    letterSpacing: 0,
  },
  h6: {
    fontFamily: FONT_BATIK_BOLD,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
    letterSpacing: 0,
  },
  mobileHeadline2: {
    fontFamily: FONT_BATIK_BOLD,
    fontSize: 19,
    fontWeight: '700',
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleBold: {
    fontFamily: FONT_POPPINS_SEMIBOLD,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    letterSpacing: 0,
  },
  titleRegular: {
    fontFamily: FONT_POPPINS_REGULAR,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: 0,
  },
  body1Bold: {
    fontFamily: FONT_POPPINS_SEMIBOLD,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: 0,
  },
  body1Regular: {
    fontFamily: FONT_POPPINS_REGULAR,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
  },
  body1CapsBold: {
    fontFamily: FONT_POPPINS_SEMIBOLD,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  body1CapsRegular: {
    fontFamily: FONT_POPPINS_REGULAR,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  strikeNumber: {
    fontFamily: FONT_POPPINS_REGULAR,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
    textDecorationLine: 'line-through',
  },
  body2Bold: {
    fontFamily: FONT_POPPINS_SEMIBOLD,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: 0,
  },
  body2Regular: {
    fontFamily: FONT_POPPINS_REGULAR,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
  },
  labelBold: {
    fontFamily: FONT_POPPINS_SEMIBOLD,
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: 0,
  },
  labelRegular: {
    fontFamily: FONT_POPPINS_REGULAR,
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 1.5,
  },
  labelSmallRegular: {
    fontFamily: FONT_POPPINS_REGULAR,
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0,
  },
  categoryMedium: {
    fontFamily: FONT_POPPINS_MEDIUM,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0,
  },
} as const;

export type TypographyToken = keyof typeof typography;
