sonar.projectKey=Schitzos_mbc-nfc
sonar.organization=schitzos
sonar.projectName=mbc-nfc

sonar.sources=src
sonar.tests=src,__tests__
sonar.test.inclusions=src/**/__tests__/**/*.ts,src/**/__tests__/**/*.tsx,__tests__/**/*.ts,__tests__/**/*.tsx
sonar.exclusions=android/**,ios/**,coverage/**,test-results/**,node_modules/**,src/**/*.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8
